dubbo:
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: spring-cloud://localhost #使用spring-cloud注册中心 这样会使用nacos地址
    timeout: 100000

spring:
  application:
    name: spring-cloud-dubbo-provider-20880
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.200:8848
#    zookeeper:
#      discovery:
#        register: true #表示服务是否需要注册到注册中心
#      connect-string: 192.168.3.200:2181 #表示ZooKeeper的连接字符串
