dubbo:
  protocol:
    port: 20880
    name: dubbo

spring:
  application:
    name: spring-cloud-dubbo-provider-zookeeper
  cloud:
    zookeeper:
      discovery:
        register: true #表示服务是否需要注册到注册中心
      connect-string: 192.168.3.200:2181 #表示ZooKeeper的连接字符串
