dubbo:
  cloud:
    subscribed-services: spring-cloud-dubbo-provider-zookeeper

spring:
  application:
    name: spring-cloud-dubbo-consumer
  cloud:
    zookeeper:
      discovery:
        register: false #表示服务是否需要注册到注册中心
      connect-string: 192.168.3.200:2181 #表示ZooKeeper的连接字符串
